package com.terakoya76.debeziumsample.model;

import java.nio.ByteBuffer;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

// https://github.com/debezium/debezium/blob/9b405aa84d8391a7ccf883184d6e8c67bac8bed3/debezium-core/src/main/java/io/debezium/relational/history/HistoryRecord.java
@DynamoDBTable(tableName = "histories")
public class History {
    private String instanceId;
    private String id;
    private String document;

    @DynamoDBHashKey(attributeName = "instance_id")
    public String getInstanceId() {
        return instanceId;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id")
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "document")
    public String getDocument() {
        return document;
    }

    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setDocument(String document) {
        this.document = document;
    }
}
